### ISSUE TITLE
CARD & Hovernet model not working

### ISSUE THREAD

**Issue by Radesh-NMP** [Sanofi-Public/spatialone-pipeline#4]
Hello, 

Thank you for sharing the Spatialone pipeline, it's very interesting and user-friendly. We were able to run the pipeline using the default models provided in the tutorial, but when switched to the "CARD" & "Hovernet" model, the pipeline threw an error. 

In regard to the Hovernet model, there was a http connection error and 

numpy to R object conversion error for the CARD model. 

Appreciate it very much if you could provide some feedback in regards to running the pipeline with CARD & Hovernet model. 

Thanks,
Radesh

**Comment by AlbertPlaPlanas** [comment]
Hi @Radesh-NMP can you share the exact error you got and details bout the execution you attempted?

Which config file and dataset(s) did you use?

**Comment by AlbertPlaPlanas** [comment]
The CARD error seems to be related to a few latest releases of python packages used by reticulate. We'll work on locking the python packages used in the CARD container and release it. 

The Hovernet error is caused by a formatting error in the `type_info.json` in the file downloaded from zenodo. A temporal fix would be to remove the last comma of the file so it has the following format:
```json
{
    "0" : ["nolabel", [0  ,   0,   0]], 
    "1" : ["Neutrophil", [255,   0,   0]], 
    "2" : ["Epithelial", [0  , 255,   0]], 
    "3" : ["Lymphocyte", [0  ,   0, 255]], 
    "4" : ["Plasma", [255, 255,   0]], 
    "5" : ["Eosinophil", [255, 165,   0]]
}
```
We'll update the file in Zenodo (and any link pointing to it)

**Comment by Radesh-NMP** [comment]
> Hi @Radesh-NMP can you share the exact error you got and details bout the execution you attempted?
> 
> Which config file and dataset(s) did you use?

Hello @AlbertPlaPlanas  we used the Mouse kidney dataset provided in the Zenodo website and the default config file present in the repo. 

It would be great if we can discuss more about this over a call and please let me know when would be a good time to set up a meeting. My email id is Radesh.n@zifornd.com. Looking forward to hearing back from you. Thanks. Radesh

**Comment by Radesh-NMP** [comment]
> The CARD error seems to be related to a few latest releases of python packages used by reticulate. We'll work on locking the python packages used in the CARD container and release it.
> 
> The Hovernet error is caused by a formatting error in the `type_info.json` in the file downloaded from zenodo. A temporal fix would be to remove the last comma of the file so it has the following format:
> 
> ```json
> {
>     "0" : ["nolabel", [0  ,   0,   0]], 
>     "1" : ["Neutrophil", [255,   0,   0]], 
>     "2" : ["Epithelial", [0  , 255,   0]], 
>     "3" : ["Lymphocyte", [0  ,   0, 255]], 
>     "4" : ["Plasma", [255, 255,   0]], 
>     "5" : ["Eosinophil", [255, 165,   0]]
> }
> ```
> 
> We'll update the file in Zenodo (and any link pointing to it)

Hello @AlbertPlaPlanas, Thank you for the update.

**Comment by AlbertPlaPlanas** [comment]
We have updated our readme files and tutorials to point to the corrected `type_info.json` in zenodo.

We also have also identified the issue with CARD and have implemented a fix for it, that we are now testing. 
We expect to issue a PR with these fixes in the next days.

**Comment by AlbertPlaPlanas** [comment]
We have issued a PR solving this issue https://github.com/Sanofi-Public/spatialone-pipeline/pull/10
