### ISSUE TITLE
CytAssist_11mm_FFPE_Human_Lung_Cancer sample failing to run & throws error

### ISSUE THREAD

**Issue by ahkamzifo** [Sanofi-Public/spatialone-pipeline#9]
Hi, 
Thanks for the amazing work on putting up this pipeline. I got an opportunity to test the pipeline along with my colleague Radesh-NMP. While running the particular dataset (**CytAssist_11mm_FFPE_Human_Lung_Cancer**) under default parameters, I am getting the following error at the image segmentation step. I have attached part of the screenshot of the error log below:

![image](https://github.com/user-attachments/assets/2d5dd542-3512-4127-822e-d4fc3b0c182b)

While tracking the computational metric for the particular run, the step before interruption seems to take more than 128 GB of available RAM. 

![image](https://github.com/user-attachments/assets/9cdde3ed-feaf-4bd7-aa1e-4c5a9b70a38d)

The server configuration for the above sample run is given below:
g5.8xlarge instance type, 128 GB RAM, and 32 CPU 

Do you have any suggestion/recommendations on how to overcome this error?

**Comment by AlbertPlaPlanas** [comment]
You are right, the issue you are facing is due to running out of memory. 
The requirements we defined were based on other samples with a smaller WSI.tif, we have updated the requirements in the readme.

Our examples with the CytAssist_11mm_FFPE_Human_Lung_Cancer image were generated using a p3.8xlarge machine. I imagine that g5.16xlarge or g6.16xlarge can also do the job (but we haven't tried)

**Comment by AlbertPlaPlanas** [comment]
I confirm that the analysis can be run with a g5.16xlarge

**Comment by ahkamzifo** [comment]
> I confirm that the analysis can be run with a g5.16xlarge

@AlbertPlaPlanas Thanks for the reply. We tried running the CytAssist_11mm_FFPE_Human_Lung_Cancer sample in the g5.16xlarge for three times. But exactly at the same step it was failing for the specific sample.

**Comment by mathewsunaal** [comment]
@ahkamzifo Is there a way you can share the RAM used by g5.16xlarge instance during the run? This way we can investigate if it is a memory bound issue.

**Comment by ahkamzifo** [comment]
@mathewsunaal Please find the screenshots of RAM usage and logs for the failed run below:
![image](https://github.com/user-attachments/assets/37dcd443-bf37-463c-8c6a-01a2a241018f)
The vms, rss and shared column are in bytes. The screenshot of log file is given below:

![image](https://github.com/user-attachments/assets/3e4ec2de-2265-460c-840a-5ae16cc6feff)
